name: CI
run-name: CI on ${{ github.ref_name }}

on:
  push:
    paths:
      - '**.lua'
      - 'justfile'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.lua'
      - 'justfile'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  lua_check:
    name: Lua Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v4

      - name: Setup poof and install packages
        uses: pirafrank/poof@main
        with:
          packages: |
            JohnnyMorganz/StyLua

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.4"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run Lua checks
        run: just ci
